version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - api-gateway
      - cubejs
      - redis

  api:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./appsettings/api:/app/appsettings

  api-gateway:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./appsettings/api-gateway:/app/appsettings

  cubejs:
    image: cubejs/cube:latest
    container_name: cubejs
    env_file:
      - ./cubejs-new/.env
    volumes:
      - ./cubejs-new/cube:/cube/conf

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"