apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-proxy
          mountPath: /etc/nginx/proxy.conf
          subPath: proxy.conf
        - name: nginx-mime
          mountPath: /etc/nginx/mime.types
          subPath: mime.types
        - name: nginx-ssl
          mountPath: /etc/nginx/ssl
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-proxy
        configMap:
          name: nginx-proxy
      - name: nginx-mime
        configMap:
          name: nginx-mime
      - name: nginx-ssl
        secret:
          secretName: nginx-ssl
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
    - port: 443
      targetPort: 443
      nodePort: 30443
  selector:
    app: nginx 